import { StyleSheet } from "react-native";
import colors from "../../../../../config/colors";
import fontSize from "../../../../../config/fontSize";

const styles = StyleSheet.create({
   LogoBox: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
      width: "100%",
      height: 300,
      backgroundColor: colors.bl0,
   },
   appBadge: {
      position: "absolute",
      height: 25,
      borderRadius: 5,
      backgroundColor: colors.bl1,
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
   },
   imageButton: {
      width: 80,
      height: 80,
      borderRadius: 50,
      backgroundColor: colors.bk0,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
   },
   infoBox: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
   },
   nameText: {
      fontSize: fontSize.veryLarge,
      fontStyle: "italic",
      borderRadius: 10,
   },
   descriptionText: {
      fontSize: fontSize.normal,
      fontStyle: "italic",
      textAlign: "center",
      paddingTop: 5,
      borderRadius: 10,
   },
   characterCounterFloatBox: {
      zIndex: 1,
      position: 'absolute',
      right: 0,
      top: -2,
      width: 55,
      height: 17,
      display: 'flex', 
      flexDirection: 'row', 
      justifyContent: 'space-between',
   },
   characterCounter: {
      fontSize: fontSize.small, 
      width: 35, 
      borderRadius: 10, 
      backgroundColor: colors.bl1,
   },
   checkButton: {
      width: 17,
      height: 17,
      borderRadius: 50,
      backgroundColor: colors.bl1,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
   },
   boxModal: {
      position: "absolute",
      top: 160,
      left: 20,
      width: "90%",
      height: 125,
      borderRadius: 10,
      backgroundColor: colors.wh0,
      display: "flex",
      justifyContent: "space-evenly",
      alignItems: "center",
   },
   input: {
      width: "95%",
      height: 35,
      borderRadius: 5,
      color: colors.bk1,
      backgroundColor: colors.wh1,
   },
   buttonBox: {
      width: "95%",
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-end",
   },
   backButton: {
      width: 100,
      height: 35,
      borderRadius: 5,
      backgroundColor: colors.wh1,
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
   },
   changeButton: {
      width: 80,
      height: 35,
      borderRadius: 5,
      marginLeft: 5,
      backgroundColor: colors.bl0,
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
   },
});

export default styles;